name: Build

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        include:

          - os: ubuntu-latest
            arch: x64

          - os: ubuntu-24.04-arm
            arch: arm64

          - os: windows-latest
            arch: x64

          - os: windows-11-arm
            arch: arm64

          - os: macos-latest
            arch: arm64

          - os: macos-13
            arch: x64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v5

    - name: Install Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"

    - name: Install dependencies
      run:

        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build
      run:

        pyinstaller --onefile main.py

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Flowerie_bot-${{ matrix.os }}
        path: dist/
